[package]
name = "protos-rs"
version = "0.1.0"
authors = ["Antoine Altorffer <altorantoine@hotmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24"
egui_node_graph="0.4.0"
anyhow = "1.0"
serde = { version = "1.0", optional = true }
egui_wgpu_backend = "0.19"
chrono = "0.4"
pollster = "0.2"
bytemuck = { version = "1.4", features = [ "derive" ] }
egui = "0.19"
epi = "0.17"
egui_winit_platform = "0.16"
wgpu ="0.13"
winit = { version="0.27.3", features = ["x11"]}
backtrace = "0.3.69"
eframe = "0.25.0"
serde_json = "1.0.111"


[features]
default = ["persistence"]
persistence = ["serde", "egui_node_graph/persistence", "egui/persistence", "wgpu/trace", "wgpu/replay"]

[profile.release]
opt-level = 2 # fast and small wasm
